"""Added password field to User model

Revision ID: 94844424f70f
Revises: fbf76c4c5807
Create Date: 2025-03-10 21:30:48.657281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94844424f70f'
down_revision = 'fbf76c4c5807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))
        batch_op.alter_column('gender',
               existing_type=postgresql.ENUM('Male', 'Female', name='gender_enum'),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.String(length=10),
               type_=postgresql.ENUM('Male', 'Female', name='gender_enum'),
               existing_nullable=False)
        batch_op.drop_column('password')

    # ### end Alembic commands ###
