"""Fixed ENUM issues

Revision ID: fbf76c4c5807
Revises: 
Create Date: 2025-03-10 11:22:29.671734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbf76c4c5807'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', name='gender_enum'), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('town', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('approval_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matched_user_id', sa.Integer(), nullable=False),
    sa.Column('requesting_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Approved', 'Declined', name='approval_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['matched_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age_range', sa.String(length=50), nullable=False),
    sa.Column('town', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('self_description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level_of_education', sa.String(length=100), nullable=False),
    sa.Column('profession', sa.String(length=100), nullable=False),
    sa.Column('marital_status', sa.Enum('Single', 'Married', 'Divorced', name='marital_status_enum'), nullable=False),
    sa.Column('religion', sa.Enum('Christian', 'Muslim', 'Other', name='religion_enum'), nullable=False),
    sa.Column('ethnicity', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('matched_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['matched_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['match_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    op.drop_table('user_details')
    op.drop_table('self_description')
    op.drop_table('message')
    op.drop_table('match_request')
    op.drop_table('approval_request')
    op.drop_table('user')
    # ### end Alembic commands ###
